### ISSUE TITLE
Investigate timeouts on the migrate_user endpoint

### ISSUE THREAD

**Issue by caspervdw** [lizardsystem/lizard-auth-server#105]
The call to the migrate_user endpoint takes more than 1 second sometimes.

This should be investigated.

I suspect the SQL query to be the culprit. We can probably add a weird index to optimize this query. On production the table is larger so this issue becomes larger too.

**Comment by caspervdw** [comment]
Quickfix: https://github.com/nens/tf-cognito/pull/38

**Comment by caspervdw** [comment]
This is not an issue anymore after the increase of the timeout and the simplification of the query.

**Comment by caspervdw** [comment]
This was a mistake in the server itself. The server was continuously overloaded. Solved in https://github.com/nens/sso/pull/24

**Comment by lexvand** [comment]
No more timeouts.
