### ISSUE TITLE
URL voor na het activeren door kunnen geven

### ISSUE THREAD

**Issue by reinout** [lizardsystem/lizard-auth-server#61]
Na het activeren van je account krijg je een linkje "ga naar het portaal dat jouw account heeft aangevraagd".

Als een server meerdere hostnames heeft zou het lekker zijn als de hostname die daar staat instelbaar is. Default is het de `visit_url` van de `Portal`.

**Comment by byrman** [comment]
Ik ga dit meegeven in de signed message d.m.v. request.get_host(). Hoe zal ik het veld noemen: host? Of visit_url? Of iets anders?

https://docs.djangoproject.com/en/1.10/ref/request-response/#django.http.HttpRequest.get_host

**Comment by reinout** [comment]
request.build_absolute_uri('/') is wat ik zelf gebruik.

https://github.com/lizardsystem/lizard-auth-server/blob/8355cc8d15c00b7e4683b8101ac9c55143de6f04/lizard_auth_server/views_api_v2.py#L92

visit_url lijkt me een mooie naam

**Comment by byrman** [comment]
Houdt die wel rekening met HTTP_X_FORWARDED_HOST headers?

Ik zal er `visit_url` van maken.

**Comment by reinout** [comment]
Jahoor, dat doet íe. Zit ook al in lizard-auth-client in het stukje code dat de ga-hierheen-na-inloggen url doorstuurt. Dat werkt nu ook goed met apeldoorn.lizard.net enzo.
