### ISSUE TITLE
Django updaten naar 2.2 LTS

### ISSUE THREAD

**Issue by jpprins1** [lizardsystem/lizard-auth-server#72]
Django = 1.9.X wordt sinds april 2017 niet meer gesupport.

Nb. Mssn idee om dit direct ook in kaart te brengen voor alle projecten? Dan kunnen we lijstje maken welke allemaal nog moeten en even verdelen wie welke gaat updaten ;)

**Comment by reinout** [comment]
De afdeling archiefstukken zit één verdieping boven je :-)

Er zijn wel lijstjes. Vooral i.v.m. het updaten van alles naar https (net gisteren is de allerlaatste externe site naar https gegaan) en van het uitfaseren van ubuntu 12.04. Aaargh.

**Comment by jpprins1** [comment]
Hahaha ok ;-) 

Goed bezig! :+1:

**Comment by caspervdw** [comment]
Ik heb de versie in de titel maar even aangepast, 1.11 is inmiddels niet meer in support.

**Comment by reinout** [comment]
Ik geloof dat de helft van de infra niet meer in support is :-)

**Comment by lexvand** [comment]
@reinout Kan dit issue afgesloten worden?

**Comment by reinout** [comment]
Ja, het is nu 2.2
