### ISSUE TITLE
Add N&S AD as identity provider in AWS Cognito

### ISSUE THREAD

**Issue by caspervdw** [lizardsystem/lizard-auth-server#95]
We think this is already possible (over SAML) because Google also makes use of our AD.

Some reading:
https://aws.amazon.com/blogs/mobile/building-adfs-federation-for-your-web-app-using-amazon-cognito-user-pools/

**Comment by reinout** [comment]
For google, we use a script on our AD that exports users to google whenever there's a change. (That doesn't always work well, as I've still got my old password on google...)

For cognito, the handiest way seems to connect cognito to azure. There was a project with OGD to change our local AD to a hosted azure AD, which would be perfect for that. Only the OGD report was somewhat limited and somewhat low on detail.
Wim can "click together" something on Azure fairly soon, but you can only do that once. Some of the choices you make are fixed. So he'd prefer waiting on an answer from OGD on some specific questions.

**Comment by caspervdw** [comment]
That seems to be like a big transition! Do we keep our local AD then, or do we need to change all AD connections?

**Comment by reinout** [comment]
Well, the short term solution would be a one-way sync towards azure.
Originally the wish/aim/plan was/is to move to fully hosted ad/mail/documents, even.

I'll look at your link to see if that's a possible temp solution (though we really want something permanent).
