### ISSUE TITLE
Configure the AWS migration trigger

### ISSUE THREAD

**Issue by caspervdw** [lizardsystem/lizard-auth-server#97]
For the user migration from SSO to AWS Cognito user pool we are going to user a "migration trigger" lambda function.

See:
https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-migrate-user.html#cognito-user-pools-lambda-trigger-syntax-user-migration

This function should be written based on the endpoint developed in #96

**Comment by caspervdw** [comment]
This needs proper version management as well. I think this is the time to set up Terraform (https://www.terraform.io/) and check in the full AWS config in a repo. @reinout  what do you think of tools like terraform? Any preferences?

**Comment by reinout** [comment]
Terraform +1!

**Comment by caspervdw** [comment]
Ref. https://github.com/nens/tf-cognito
