### ISSUE TITLE
Disable the "edit_profile" view

### ISSUE THREAD

**Issue by caspervdw** [lizardsystem/lizard-auth-server#99]
Note that the lizard client links to the edit_profile view. It needs a "temporarily disabled" page or something.

**Comment by caspervdw** [comment]
Related to https://github.com/nens/lizard-client/issues/1148

**Comment by lexvand** [comment]
@byrman https://sso.staging.lizard.net/edit_profile/ is still available. Probably requires a release of SSO.

**Comment by caspervdw** [comment]
Correct, this has been released and is already on production.

**Comment by lexvand** [comment]
Check.
